/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Donation {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'acceptedByNgoId' : [] | [Principal],
  'status' : DonationStatus,
  'donorId' : Principal,
  'createdAt' : Time,
  'expiryDescription' : string,
  'address' : string,
  'notes' : string,
  'quantity' : string,
  'acceptedByNgoName' : [] | [string],
  'foodType' : string,
}
export type DonationStatus = { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'accepted' : null };
export interface FoodBridgeUser {
  'id' : Principal,
  'lat' : number,
  'lng' : number,
  'organizationName' : string,
  'contact' : string,
  'name' : string,
  'role' : { 'ngo' : null } |
    { 'donor' : null },
  'address' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDonation' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAvailableDonations' : ActorMethod<[], Array<Donation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [FoodBridgeUser]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonationById' : ActorMethod<[bigint], [] | [Donation]>,
  'getMyDonations' : ActorMethod<[], Array<Donation>>,
  'getProfile' : ActorMethod<[], [] | [FoodBridgeUser]>,
  'getProfileById' : ActorMethod<[Principal], [] | [FoodBridgeUser]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [FoodBridgeUser]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPickedUp' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[FoodBridgeUser], undefined>,
  'saveProfile' : ActorMethod<
    [
      { 'ngo' : null } |
        { 'donor' : null },
      string,
      string,
      string,
      number,
      number,
      string,
    ],
    FoodBridgeUser
  >,
  'submitDonation' : ActorMethod<
    [string, string, string, string, number, number, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];