/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DonationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'acceptedByNgoId' : IDL.Opt(IDL.Principal),
  'status' : DonationStatus,
  'donorId' : IDL.Principal,
  'createdAt' : Time,
  'expiryDescription' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Text,
  'acceptedByNgoName' : IDL.Opt(IDL.Text),
  'foodType' : IDL.Text,
});
export const FoodBridgeUser = IDL.Record({
  'id' : IDL.Principal,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'organizationName' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'ngo' : IDL.Null, 'donor' : IDL.Null }),
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDonation' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAvailableDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FoodBridgeUser)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationById' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
  'getMyDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(FoodBridgeUser)], ['query']),
  'getProfileById' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FoodBridgeUser)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FoodBridgeUser)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPickedUp' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([FoodBridgeUser], [], []),
  'saveProfile' : IDL.Func(
      [
        IDL.Variant({ 'ngo' : IDL.Null, 'donor' : IDL.Null }),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [FoodBridgeUser],
      [],
    ),
  'submitDonation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DonationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'acceptedByNgoId' : IDL.Opt(IDL.Principal),
    'status' : DonationStatus,
    'donorId' : IDL.Principal,
    'createdAt' : Time,
    'expiryDescription' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Text,
    'acceptedByNgoName' : IDL.Opt(IDL.Text),
    'foodType' : IDL.Text,
  });
  const FoodBridgeUser = IDL.Record({
    'id' : IDL.Principal,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'organizationName' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'ngo' : IDL.Null, 'donor' : IDL.Null }),
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDonation' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAvailableDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FoodBridgeUser)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationById' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
    'getMyDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(FoodBridgeUser)], ['query']),
    'getProfileById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FoodBridgeUser)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FoodBridgeUser)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPickedUp' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([FoodBridgeUser], [], []),
    'saveProfile' : IDL.Func(
        [
          IDL.Variant({ 'ngo' : IDL.Null, 'donor' : IDL.Null }),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [FoodBridgeUser],
        [],
      ),
    'submitDonation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };