/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donation {
    id: bigint;
    lat: number;
    lng: number;
    acceptedByNgoId?: Principal;
    status: DonationStatus;
    donorId: Principal;
    createdAt: Time;
    expiryDescription: string;
    address: string;
    notes: string;
    quantity: string;
    acceptedByNgoName?: string;
    foodType: string;
}
export type Time = bigint;
export interface FoodBridgeUser {
    id: Principal;
    lat: number;
    lng: number;
    organizationName: string;
    contact: string;
    name: string;
    role: Variant_ngo_donor;
    address: string;
}
export enum DonationStatus {
    pending = "pending",
    pickedUp = "pickedUp",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_ngo_donor {
    ngo = "ngo",
    donor = "donor"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptDonation(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllDonations(): Promise<Array<Donation>>;
    getAvailableDonations(): Promise<Array<Donation>>;
    getCallerUserProfile(): Promise<FoodBridgeUser | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonationById(id: bigint): Promise<Donation | null>;
    getMyDonations(): Promise<Array<Donation>>;
    getProfile(): Promise<FoodBridgeUser | null>;
    getProfileById(id: Principal): Promise<FoodBridgeUser | null>;
    getUserProfile(user: Principal): Promise<FoodBridgeUser | null>;
    isCallerAdmin(): Promise<boolean>;
    markPickedUp(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: FoodBridgeUser): Promise<void>;
    saveProfile(role: Variant_ngo_donor, name: string, organizationName: string, address: string, lat: number, lng: number, contact: string): Promise<FoodBridgeUser>;
    submitDonation(foodType: string, quantity: string, expiryDescription: string, address: string, lat: number, lng: number, notes: string): Promise<bigint>;
}
import type { Donation as _Donation, DonationStatus as _DonationStatus, FoodBridgeUser as _FoodBridgeUser, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptDonation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDonation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDonations();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDonations();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<FoodBridgeUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationById(arg0: bigint): Promise<Donation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDonations();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDonations();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<FoodBridgeUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileById(arg0: Principal): Promise<FoodBridgeUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<FoodBridgeUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markPickedUp(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPickedUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPickedUp(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: FoodBridgeUser): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_FoodBridgeUser_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_FoodBridgeUser_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProfile(arg0: Variant_ngo_donor, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string): Promise<FoodBridgeUser> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(to_candid_variant_n19(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_FoodBridgeUser_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(to_candid_variant_n19(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_FoodBridgeUser_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitDonation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDonation(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDonation(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_DonationStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationStatus): DonationStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FoodBridgeUser_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodBridgeUser): FoodBridgeUser {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodBridgeUser]): FoodBridgeUser | null {
    return value.length === 0 ? null : from_candid_FoodBridgeUser_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donation]): Donation | null {
    return value.length === 0 ? null : from_candid_Donation_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    lat: number;
    lng: number;
    organizationName: string;
    contact: string;
    name: string;
    role: {
        ngo: null;
    } | {
        donor: null;
    };
    address: string;
}): {
    id: Principal;
    lat: number;
    lng: number;
    organizationName: string;
    contact: string;
    name: string;
    role: Variant_ngo_donor;
    address: string;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        organizationName: value.organizationName,
        contact: value.contact,
        name: value.name,
        role: from_candid_variant_n13(_uploadFile, _downloadFile, value.role),
        address: value.address
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lat: number;
    lng: number;
    acceptedByNgoId: [] | [Principal];
    status: _DonationStatus;
    donorId: Principal;
    createdAt: _Time;
    expiryDescription: string;
    address: string;
    notes: string;
    quantity: string;
    acceptedByNgoName: [] | [string];
    foodType: string;
}): {
    id: bigint;
    lat: number;
    lng: number;
    acceptedByNgoId?: Principal;
    status: DonationStatus;
    donorId: Principal;
    createdAt: Time;
    expiryDescription: string;
    address: string;
    notes: string;
    quantity: string;
    acceptedByNgoName?: string;
    foodType: string;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        acceptedByNgoId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.acceptedByNgoId)),
        status: from_candid_DonationStatus_n7(_uploadFile, _downloadFile, value.status),
        donorId: value.donorId,
        createdAt: value.createdAt,
        expiryDescription: value.expiryDescription,
        address: value.address,
        notes: value.notes,
        quantity: value.quantity,
        acceptedByNgoName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.acceptedByNgoName)),
        foodType: value.foodType
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    donor: null;
}): Variant_ngo_donor {
    return "ngo" in value ? Variant_ngo_donor.ngo : "donor" in value ? Variant_ngo_donor.donor : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    pickedUp: null;
} | {
    accepted: null;
}): DonationStatus {
    return "pending" in value ? DonationStatus.pending : "pickedUp" in value ? DonationStatus.pickedUp : "accepted" in value ? DonationStatus.accepted : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n4(_uploadFile, _downloadFile, x));
}
function to_candid_FoodBridgeUser_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodBridgeUser): _FoodBridgeUser {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    lat: number;
    lng: number;
    organizationName: string;
    contact: string;
    name: string;
    role: Variant_ngo_donor;
    address: string;
}): {
    id: Principal;
    lat: number;
    lng: number;
    organizationName: string;
    contact: string;
    name: string;
    role: {
        ngo: null;
    } | {
        donor: null;
    };
    address: string;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        organizationName: value.organizationName,
        contact: value.contact,
        name: value.name,
        role: to_candid_variant_n19(_uploadFile, _downloadFile, value.role),
        address: value.address
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_ngo_donor): {
    ngo: null;
} | {
    donor: null;
} {
    return value == Variant_ngo_donor.ngo ? {
        ngo: null
    } : value == Variant_ngo_donor.donor ? {
        donor: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
